jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
spring.mongodb.connection-string=${MONGO_URI}
spring.data.mongodb.database=taskmanager

logging.level.org.springframework.data.mongodb=DEBUG

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,env
management.health.mongo.enabled=false