jwt.secret=istilllovenehaimisshermaybeiwanthertochasemebutikshewillnot
jwt.expiration=86400000

spring.mongodb.connection-string=mongodb+srv://swaroop:29102002@cluster0.htxs4ve.mongodb.net/taskmanager?appName=Cluster0
spring.data.mongodb.database=taskmanager
logging.level.org.springframework.data.mongodb=DEBUG